# -*- coding: utf-8 -*-
"""
group_music.py

Pure-Python port of the SageMath group-music experiment.

Dependencies:
    pip install mido mpmath

No SageMath, MIDIUtil, or local MidiFile.py is required.

The module contains:
  * a small finite-group / permutation toolkit,
  * constructors for common finite groups,
  * the original group_music() idea,
  * a mido-based MIDI writer.

Permutation convention
----------------------
A Permutation stores a 0-based vector p with p[i] = image of i.
Multiplication is function composition:

    (p * q)(i) = p(q(i)).

For a finite group G, regular_action_permutations() returns the permutations
x -> g*x (or x -> x*g) on the ordered set of elements of G.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from itertools import permutations as iter_permutations, product
from math import floor
from typing import Any, Iterable, Iterator, Sequence


# =============================================================================
# Permutations and finite groups
# =============================================================================


@dataclass(frozen=True)
class Permutation:
    """Finite 0-based permutation."""

    images: tuple[int, ...]

    def __init__(self, images: Sequence[int]):
        images = tuple(int(x) for x in images)
        if sorted(images) != list(range(len(images))):
            raise ValueError(f"Not a permutation: {images}")
        object.__setattr__(self, "images", images)

    @property
    def degree(self) -> int:
        return len(self.images)

    def __call__(self, i: int) -> int:
        return self.images[i]

    def __mul__(self, other: "Permutation") -> "Permutation":
        """Composition self ∘ other."""
        if not isinstance(other, Permutation) or self.degree != other.degree:
            return NotImplemented
        return Permutation([self.images[other.images[i]] for i in range(self.degree)])

    def inverse(self) -> "Permutation":
        inv = [0] * self.degree
        for i, j in enumerate(self.images):
            inv[j] = i
        return Permutation(inv)

    def is_identity(self) -> bool:
        return self.images == tuple(range(self.degree))

    def cycles(self, include_fixed: bool = False) -> list[tuple[int, ...]]:
        seen = [False] * self.degree
        out: list[tuple[int, ...]] = []
        for i in range(self.degree):
            if seen[i]:
                continue
            cyc = []
            j = i
            while not seen[j]:
                seen[j] = True
                cyc.append(j)
                j = self.images[j]
            if include_fixed or len(cyc) > 1:
                out.append(tuple(cyc))
        return out

    def __repr__(self) -> str:
        cycles = self.cycles()
        if not cycles:
            return "()"
        return "".join("(" + " ".join(str(x + 1) for x in c) + ")" for c in cycles)


class FiniteGroup:
    """Minimal protocol used by the music algorithms."""

    def __iter__(self) -> Iterator[Any]:
        raise NotImplementedError

    def elements(self) -> list[Any]:
        return list(iter(self))

    def order(self) -> int:
        return len(self.elements())

    def identity(self) -> Any:
        raise NotImplementedError

    def generators(self) -> list[Any]:
        return []

    def degree(self) -> int:
        raise TypeError("This group has no distinguished natural permutation degree.")


class PermutationGroup(FiniteGroup):
    """Finite permutation group generated by explicit permutations."""

    def __init__(self, generators: Sequence[Permutation], degree: int | None = None):
        gens = list(generators)
        if degree is None:
            if not gens:
                raise ValueError("degree is required for a trivial permutation group")
            degree = gens[0].degree
        self._degree = int(degree)
        if self._degree <= 0:
            raise ValueError("degree must be positive")
        for g in gens:
            if g.degree != self._degree:
                raise ValueError("all generators must have the same degree")
        self._gens = gens[:] if gens else [Permutation(range(self._degree))]
        self._elements = self._closure(self._gens)

    def _closure(self, gens: Sequence[Permutation]) -> list[Permutation]:
        e = Permutation(range(self._degree))
        seen = {e}
        ordered = [e]
        q = deque([e])
        # Including inverses makes closure generation much faster for some groups.
        steps = list(gens)
        for g in gens:
            gi = g.inverse()
            if gi not in steps:
                steps.append(gi)
        while q:
            a = q.popleft()
            for g in steps:
                for b in (g * a, a * g):
                    if b not in seen:
                        seen.add(b)
                        ordered.append(b)
                        q.append(b)
        return ordered

    def __iter__(self) -> Iterator[Permutation]:
        return iter(self._elements)

    def order(self) -> int:
        return len(self._elements)

    def identity(self) -> Permutation:
        return Permutation(range(self._degree))

    def generators(self) -> list[Permutation]:
        return list(self._gens)

    def degree(self) -> int:
        return self._degree

    def __repr__(self) -> str:
        return f"PermutationGroup(order={self.order()}, degree={self.degree()})"


@dataclass(frozen=True)
class AbelianElement:
    moduli: tuple[int, ...]
    coords: tuple[int, ...]

    def __mul__(self, other: "AbelianElement") -> "AbelianElement":
        if not isinstance(other, AbelianElement) or self.moduli != other.moduli:
            return NotImplemented
        return AbelianElement(
            self.moduli,
            tuple((a + b) % m for a, b, m in zip(self.coords, other.coords, self.moduli)),
        )

    def __repr__(self) -> str:
        return str(self.coords)


class AbelianGroup(FiniteGroup):
    """Direct product C_n1 x ... x C_nk, written multiplicatively in the API."""

    def __init__(self, moduli: Sequence[int]):
        self.moduli = tuple(int(m) for m in moduli)
        if not self.moduli or any(m <= 0 for m in self.moduli):
            raise ValueError("moduli must be positive integers")
        self._elements = [
            AbelianElement(self.moduli, tuple(c))
            for c in product(*(range(m) for m in self.moduli))
        ]

    def __iter__(self) -> Iterator[AbelianElement]:
        return iter(self._elements)

    def identity(self) -> AbelianElement:
        return AbelianElement(self.moduli, (0,) * len(self.moduli))

    def generators(self) -> list[AbelianElement]:
        out = []
        for i, m in enumerate(self.moduli):
            if m == 1:
                continue
            c = [0] * len(self.moduli)
            c[i] = 1
            out.append(AbelianElement(self.moduli, tuple(c)))
        return out

    def order(self) -> int:
        n = 1
        for m in self.moduli:
            n *= m
        return n

    def __repr__(self) -> str:
        return "AbelianGroup(" + " x ".join(f"C{m}" for m in self.moduli) + ")"


@dataclass(frozen=True)
class DihedralElement:
    """r^k s^flip in D_n, with s r s = r^-1."""

    n: int
    k: int
    flip: int

    def __mul__(self, other: "DihedralElement") -> "DihedralElement":
        if not isinstance(other, DihedralElement) or self.n != other.n:
            return NotImplemented
        # (r^a s^b)(r^c s^d) = r^(a + (-1)^b c) s^(b+d)
        k = (self.k + (-1 if self.flip else 1) * other.k) % self.n
        return DihedralElement(self.n, k, (self.flip + other.flip) % 2)

    def as_permutation(self) -> Permutation:
        # natural action on vertices Z/nZ: r^k s^b : x -> k + (-1)^b x
        if self.flip:
            return Permutation([(self.k - x) % self.n for x in range(self.n)])
        return Permutation([(self.k + x) % self.n for x in range(self.n)])

    def __repr__(self) -> str:
        if self.flip:
            return f"r^{self.k}s"
        return f"r^{self.k}"


class DihedralGroup(FiniteGroup):
    """Symmetry group D_n of a regular n-gon, order 2n."""

    def __init__(self, n: int):
        self.n = int(n)
        if self.n < 2:
            raise ValueError("n must be >= 2")
        self._elements = [DihedralElement(self.n, k, b) for b in (0, 1) for k in range(self.n)]
        # put identity first explicitly
        self._elements.sort(key=lambda x: (x.flip != 0, x.k))

    def __iter__(self) -> Iterator[DihedralElement]:
        return iter(self._elements)

    def identity(self) -> DihedralElement:
        return DihedralElement(self.n, 0, 0)

    def generators(self) -> list[DihedralElement]:
        return [DihedralElement(self.n, 1, 0), DihedralElement(self.n, 0, 1)]

    def order(self) -> int:
        return 2 * self.n

    def degree(self) -> int:
        return self.n

    def natural_permutations(self) -> list[Permutation]:
        return [g.as_permutation() for g in self._elements]

    def __repr__(self) -> str:
        return f"DihedralGroup({self.n})"


# Q8 --------------------------------------------------------------------------

_Q_UNITS = ("1", "i", "j", "k")
_Q_BASE_MUL = {
    ("1", "1"): (1, "1"), ("1", "i"): (1, "i"), ("1", "j"): (1, "j"), ("1", "k"): (1, "k"),
    ("i", "1"): (1, "i"), ("j", "1"): (1, "j"), ("k", "1"): (1, "k"),
    ("i", "i"): (-1, "1"), ("j", "j"): (-1, "1"), ("k", "k"): (-1, "1"),
    ("i", "j"): (1, "k"), ("j", "k"): (1, "i"), ("k", "i"): (1, "j"),
    ("j", "i"): (-1, "k"), ("k", "j"): (-1, "i"), ("i", "k"): (-1, "j"),
}


@dataclass(frozen=True)
class QuaternionElement:
    sign: int
    unit: str

    def __post_init__(self):
        if self.sign not in (-1, 1) or self.unit not in _Q_UNITS:
            raise ValueError("invalid quaternion unit")

    def __mul__(self, other: "QuaternionElement") -> "QuaternionElement":
        if not isinstance(other, QuaternionElement):
            return NotImplemented
        s, u = _Q_BASE_MUL[(self.unit, other.unit)]
        return QuaternionElement(self.sign * other.sign * s, u)

    def __repr__(self) -> str:
        return ("-" if self.sign < 0 else "") + self.unit


class QuaternionGroup(FiniteGroup):
    def __init__(self):
        self._elements = [QuaternionElement(1, "1"), QuaternionElement(-1, "1")]
        for u in ("i", "j", "k"):
            self._elements.extend([QuaternionElement(1, u), QuaternionElement(-1, u)])

    def __iter__(self) -> Iterator[QuaternionElement]:
        return iter(self._elements)

    def identity(self) -> QuaternionElement:
        return QuaternionElement(1, "1")

    def generators(self) -> list[QuaternionElement]:
        return [QuaternionElement(1, "i"), QuaternionElement(1, "j")]

    def order(self) -> int:
        return 8

    def __repr__(self) -> str:
        return "QuaternionGroup(Q8)"


@dataclass(frozen=True)
class DirectProductElement:
    components: tuple[Any, ...]

    def __mul__(self, other: "DirectProductElement") -> "DirectProductElement":
        if not isinstance(other, DirectProductElement) or len(self.components) != len(other.components):
            return NotImplemented
        return DirectProductElement(tuple(a * b for a, b in zip(self.components, other.components)))


class DirectProductGroup(FiniteGroup):
    def __init__(self, groups: Sequence[FiniteGroup]):
        self.groups = tuple(groups)
        if not self.groups:
            raise ValueError("at least one factor is required")
        self._factor_elements = [list(g) for g in self.groups]
        self._elements = [DirectProductElement(tuple(x)) for x in product(*self._factor_elements)]

    def __iter__(self) -> Iterator[DirectProductElement]:
        return iter(self._elements)

    def identity(self) -> DirectProductElement:
        return DirectProductElement(tuple(g.identity() for g in self.groups))

    def generators(self) -> list[DirectProductElement]:
        ids = [g.identity() for g in self.groups]
        out = []
        for i, g in enumerate(self.groups):
            for gen in g.generators():
                c = list(ids)
                c[i] = gen
                out.append(DirectProductElement(tuple(c)))
        return out

    def order(self) -> int:
        n = 1
        for g in self.groups:
            n *= g.order()
        return n


# Common permutation groups ----------------------------------------------------


def CyclicPermutationGroup(n: int) -> PermutationGroup:
    n = int(n)
    if n < 1:
        raise ValueError("n must be positive")
    rotation = Permutation([(i + 1) % n for i in range(n)])
    return PermutationGroup([rotation], degree=n)


def SymmetricGroup(n: int) -> PermutationGroup:
    n = int(n)
    if n < 1:
        raise ValueError("n must be positive")
    if n == 1:
        return PermutationGroup([], degree=1)
    cycle = Permutation([(i + 1) % n for i in range(n)])
    trans = list(range(n))
    trans[0], trans[1] = trans[1], trans[0]
    return PermutationGroup([cycle, Permutation(trans)], degree=n)


def AlternatingGroup(n: int) -> PermutationGroup:
    n = int(n)
    if n < 2:
        return PermutationGroup([], degree=max(1, n))
    if n == 2:
        return PermutationGroup([], degree=2)
    gens = []
    # A_n is generated by 3-cycles (0,1,k), k=2,...,n-1.
    for k in range(2, n):
        p = list(range(n))
        p[0], p[1], p[k] = 1, k, 0
        gens.append(Permutation(p))
    return PermutationGroup(gens, degree=n)


def KleinFourGroup() -> PermutationGroup:
    a = Permutation([1, 0, 3, 2])  # (1 2)(3 4)
    b = Permutation([2, 3, 0, 1])  # (1 3)(2 4)
    return PermutationGroup([a, b], degree=4)


def dihedral_permutation_group(n: int) -> PermutationGroup:
    """Natural permutation representation of D_n on n vertices."""
    D = DihedralGroup(n)
    gens = [g.as_permutation() for g in D.generators()]
    return PermutationGroup(gens, degree=n)


def DirectProduct(*groups: FiniteGroup) -> DirectProductGroup:
    return DirectProductGroup(groups)


# =============================================================================
# Group actions / regular representation
# =============================================================================


def _ordered_group_elements(G: FiniteGroup, identity_first: bool = True) -> list[Any]:
    elts = list(G)
    if not identity_first or len(elts) <= 1:
        return elts
    try:
        e = G.identity()
    except Exception:
        return elts
    for i, g in enumerate(elts):
        if g == e:
            if i:
                elts = [g] + elts[:i] + elts[i + 1 :]
            break
    return elts


def regular_action_permutations(
    G: FiniteGroup,
    side: str = "left",
    identity_first: bool = True,
) -> dict[str, Any]:
    """Return all permutations of the left or right regular action of G."""
    if side not in ("left", "right"):
        raise ValueError("side must be 'left' or 'right'")
    elts = _ordered_group_elements(G, identity_first=identity_first)
    if not elts:
        raise ValueError("empty group")
    index = {g: i for i, g in enumerate(elts)}
    if len(index) != len(elts):
        raise ValueError("group elements must be hashable and distinct")

    perms = []
    for g in elts:
        images = []
        for x in elts:
            y = g * x if side == "left" else x * g
            if y not in index:
                raise ValueError(f"group multiplication left the enumerated group: {y!r}")
            images.append(index[y])
        perms.append(Permutation(images))

    return {
        "elements": elts,
        "permutations": perms,
        "degree": len(elts),
        "representation": "regular",
        "side": side,
    }


def given_action_permutations(G: FiniteGroup, identity_first: bool = True) -> dict[str, Any]:
    """Use the group's natural permutation action where available."""
    elts = _ordered_group_elements(G, identity_first=identity_first)

    if isinstance(G, PermutationGroup):
        perms = list(elts)
        d = G.degree()
    elif isinstance(G, DihedralGroup):
        perms = [g.as_permutation() for g in elts]
        d = G.degree()
    else:
        raise TypeError("given action is available for PermutationGroup and DihedralGroup")

    return {
        "elements": elts,
        "permutations": perms,
        "degree": d,
        "representation": "given",
        "side": None,
    }


def group_action_permutations(
    G: FiniteGroup,
    representation: str = "regular",
    side: str = "left",
    identity_first: bool = True,
) -> dict[str, Any]:
    if representation == "regular":
        return regular_action_permutations(G, side=side, identity_first=identity_first)
    if representation == "given":
        return given_action_permutations(G, identity_first=identity_first)
    raise ValueError("representation must be 'regular' or 'given'")


def regular_permutation_group(G: FiniteGroup, side: str = "left", return_data: bool = True):
    """Pure-Python counterpart of the old Sage regular_permutation_group()."""
    action = regular_action_permutations(G, side=side, identity_first=True)
    elts = action["elements"]
    perms = action["permutations"]
    gens = []
    gen_map = {}
    index = {g: i for i, g in enumerate(elts)}
    for gen in G.generators():
        if gen not in index:
            continue
        p = perms[index[gen]]
        gens.append(p)
        gen_map[gen] = p
    if not gens:
        gens = [Permutation(range(len(elts)))]
    P = PermutationGroup(gens, degree=len(elts))
    if P.order() != len(elts):
        raise ValueError(f"regular representation has order {P.order()} instead of {len(elts)}")
    if not return_data:
        return P
    return {
        "group": P,
        "elements": elts,
        "index": index,
        "perm_of_gen": gen_map,
        "degree": len(elts),
    }


# =============================================================================
# MIDI output for generated material (mido, no MIDIUtil)
# =============================================================================


def _require_mido():
    try:
        import mido
        return mido
    except ImportError as exc:
        raise ImportError("Install mido with: pip install mido") from exc


def write_pitches(
    filename: str,
    voices_data: Sequence[Sequence[tuple[float, float, int, bool, float]]],
    tempo: float = 82,
    instrument: Sequence[int] | None = None,
    add21: bool = True,
    start_at: Sequence[float] | None = None,
    durations_in_quarter_notes: bool = False,
    ticks_per_beat: int = 480,
) -> str:
    """
    Write the legacy voice-event representation with mido.

    Event format:
        (pitch, duration, volume, is_pause, event_tempo)

    The old code multiplied duration by 4 when durationsInQuarterNotes=False;
    this compatibility behavior is preserved.
    """
    mido = _require_mido()
    ni = len(voices_data)
    if ni == 0:
        raise ValueError("voices_data is empty")
    if ni > 16:
        raise ValueError("standard MIDI supports at most 16 channels in this simple writer")

    instruments = list(instrument) if instrument is not None else [0] * ni
    starts = list(start_at) if start_at is not None else [0.0] * ni
    instruments += [0] * max(0, ni - len(instruments))
    starts += [0.0] * max(0, ni - len(starts))

    mid = mido.MidiFile(type=1, ticks_per_beat=int(ticks_per_beat))
    tempo_msg = mido.bpm2tempo(float(tempo))

    for k, voice in enumerate(voices_data):
        track = mido.MidiTrack()
        mid.tracks.append(track)
        channel = k
        events = []
        serial = 0

        events.append((0, 0, serial, mido.MetaMessage("set_tempo", tempo=tempo_msg, time=0)))
        serial += 1
        events.append((0, 1, serial, mido.Message("program_change", channel=channel, program=max(0, min(127, int(instruments[k]))), time=0)))
        serial += 1

        current_beats = float(starts[k])
        for event in voice:
            pitch, duration, volume, is_pause, _event_tempo = event
            duration_beats = float(duration) if durations_in_quarter_notes else 4.0 * float(duration)
            duration_beats = max(0.0, duration_beats)
            start_tick = int(round(current_beats * ticks_per_beat))
            end_tick = int(round((current_beats + duration_beats) * ticks_per_beat))

            if not is_pause and duration_beats > 0:
                p = floor(float(pitch)) + (21 if add21 else 0)
                p = max(0, min(127, int(p)))
                v = max(0, min(127, int(volume)))
                events.append((start_tick, 3, serial, mido.Message("note_on", channel=channel, note=p, velocity=v, time=0)))
                serial += 1
                events.append((max(start_tick + 1, end_tick), 2, serial, mido.Message("note_off", channel=channel, note=p, velocity=0, time=0)))
                serial += 1

            current_beats += duration_beats

        events.sort(key=lambda e: (e[0], e[1], e[2]))
        last_tick = 0
        for tick, _priority, _serial, msg in events:
            track.append(msg.copy(time=max(0, tick - last_tick)))
            last_tick = tick
        track.append(mido.MetaMessage("end_of_track", time=0))

    mid.save(filename)
    print("written:", filename)
    return filename


# Legacy spelling for easy porting of old notebooks/scripts.
writePitches = write_pitches


# =============================================================================
# Group-driven composition
# =============================================================================


def _decimal_parity_bits(value: str | float | int | Any, digits: int) -> list[int]:
    """Convert decimal digits of a constant to parity bits digit mod 2."""
    try:
        import mpmath as mp
    except ImportError as exc:
        raise ImportError("Install mpmath with: pip install mpmath") from exc

    digits = max(20, int(digits))
    old_dps = mp.mp.dps
    mp.mp.dps = digits + 10
    try:
        if value is None or value == "pi":
            x = mp.pi
        elif value == "exp(-pi)":
            x = mp.exp(-mp.pi)
        elif callable(value):
            x = value(mp)
        else:
            x = mp.mpf(value)
        s = mp.nstr(x, n=digits + 2, strip_zeros=False)
    finally:
        mp.mp.dps = old_dps

    # mpmath may use scientific notation for very small/large constants.
    if "e" in s.lower():
        old_dps = mp.mp.dps
        mp.mp.dps = digits + 10
        try:
            if value is None or value == "pi":
                x = mp.pi
            elif value == "exp(-pi)":
                x = mp.exp(-mp.pi)
            elif callable(value):
                x = value(mp)
            else:
                x = mp.mpf(value)
            s = mp.nstr(x, n=digits + 2, min_fixed=-1000000, max_fixed=1000000, strip_zeros=False)
        finally:
            mp.mp.dps = old_dps

    digits_only = [ch for ch in s if ch.isdigit()]
    # Match the Sage intention: use digits after the decimal point when possible.
    if "." in s:
        frac = s.split(".", 1)[1]
        if "e" in frac.lower():
            frac = frac.lower().split("e", 1)[0]
        digits_only = [ch for ch in frac if ch.isdigit()]
    if not digits_only:
        raise ValueError("could not extract decimal digits")
    return [int(ch) % 2 for ch in digits_only]


def group_music(
    G: FiniteGroup,
    chords: Sequence[Sequence[int]],
    tempo: float = 81,
    base_duration: float = 1 / 9,
    octave_range: tuple[int, int] = (-2, 2),
    pi_nr: Any = "pi",
    pi_digits: int = 10000,
    voices: int = 4,
    chord_change_every: int = 4,
    iter_it: int = 1,
):
    """
    Pure-Python port of the original Sage group_music().

    It deliberately preserves the original iter_it behavior for compatibility:
    for iter_it > 1 the element list is expanded by concatenating regular-action
    rows.  This is musically useful but is not a higher group power.
    """
    original_elts = list(G)
    n = len(original_elts)
    if n == 0:
        raise ValueError("G must be finite and non-empty")
    if not chords:
        raise ValueError("chords must not be empty")
    if voices <= 0:
        raise ValueError("voices must be positive")
    if chord_change_every <= 0:
        raise ValueError("chord_change_every must be positive")

    elts = list(original_elts)
    if iter_it > 1:
        expanded = []
        for _ in range(iter_it - 1):
            for g in elts:
                expanded.extend(g * h for h in elts)
        elts = expanded

    idx = {g: i for i, g in enumerate(elts)}
    bits = _decimal_parity_bits(pi_nr, pi_digits)

    lines = [[] for _ in range(voices)]
    octaves = [-2 + (v % 5) for v in range(voices)]
    signs = [1] * voices
    durations = [base_duration / (1 + (v % 4)) for v in range(voices)]

    lastbit = 0
    c = 0

    for g in elts:
        orbit = [g * h for h in elts]
        chord = chords[(c // chord_change_every) % len(chords)]
        m = len(chord)
        if m == 0:
            raise ValueError("chords may not contain empty chords")
        bit = bits[c % len(bits)]

        for j, h in enumerate(orbit):
            element_index = idx[h]

            for v in range(voices):
                if v % 4 == 0:
                    degree = (element_index + v) % m
                elif v % 4 == 1:
                    degree = (-element_index - 1 + v) % m
                elif v % 4 == 2:
                    degree = (2 * element_index + v) % m
                else:
                    degree = (element_index * element_index + v) % m

                pitch = int(chord[degree]) + 12 * octaves[v]
                while pitch < 0:
                    pitch += 12
                while pitch > 127:
                    pitch -= 12

                if v % 2 == 0:
                    volume = 90 - int(50 * j / max(1, n - 1))
                else:
                    volume = 45 + int(50 * j / max(1, n - 1))
                volume -= 4 * (v // 2)
                volume = max(1, min(127, volume))

                lines[v].append((pitch, float(durations[v]), int(volume), False, tempo))

        for v in range(voices):
            if octaves[v] <= octave_range[0]:
                signs[v] = 1
            if octaves[v] >= octave_range[1]:
                signs[v] = -1

            if v % 3 == 0:
                trigger = bit == 0
            elif v % 3 == 1:
                trigger = bit == 1
            else:
                trigger = lastbit != bit

            if trigger:
                octaves[v] = min(max(octaves[v] + signs[v], octave_range[0]), octave_range[1])

        if bit == 1 and voices > 1:
            durations = durations[1:] + durations[:1]

        lastbit = bit
        c += 1

    return lines


# =============================================================================
# Harmonic material copied from the Sage version
# =============================================================================

CHORDS = [
    [62,65,69], [65,69,72], [67,71,74], [60,63,67], [60,64,67], [57,60,64],
    [55,59,62], [53,57,60], [50,53,57], [52,55,59], [59,62,65], [58,62,65],
    [60,64,67,71], [62,65,69,72], [64,67,71,74], [65,69,72,76], [67,71,74,77],
    [69,72,76,79], [59,62,65,69], [58,62,65,68], [61,65,68,71], [63,66,69,72],
    [60,63,67,70], [62,65,69,72], [65,68,72,75], [67,70,74,77], [69,72,76,79],
    [57,60,64,67], [50,53,57,60], [55,58,62,65],
    [60,65,67], [60,62,67], [62,67,69], [62,64,69], [65,70,72], [65,67,72],
    [67,72,74], [67,69,74], [69,74,76], [69,71,76],
    [60,64,67,74], [62,65,69,76], [65,69,72,79], [67,71,74,81], [57,60,64,71],
    [60,64,67,69], [62,65,69,71], [65,69,72,74], [67,71,74,76], [60,65,67,74],
    [60,64,67,71,74], [62,65,69,72,76], [64,67,71,74,78], [65,69,72,76,79],
    [67,71,74,77,81], [69,72,76,79,83], [58,62,65,68,72], [55,59,62,65,69],
    [60,63,66], [62,65,68], [64,67,70], [65,68,71], [67,70,73], [60,64,68],
    [62,66,70], [65,69,73], [67,71,75], [60,63,66,69], [62,65,68,71], [64,67,70,73],
    [60,65,70], [62,67,72], [64,69,74], [65,70,75], [67,72,77], [69,74,79],
    [60,67,74], [62,69,76], [65,72,79], [67,74,81],
    [60,62,67,69], [62,65,67,69], [64,65,71,72], [65,67,72,74], [67,69,74,77],
    [69,72,74,79], [59,60,65,67], [60,62,65,67,69], [62,65,67,69,72], [65,67,69,72,74],
    [60,64,67,70,74], [60,64,68,70], [60,64,66,70], [60,63,66,70], [62,66,69,72],
    [62,66,70,72], [62,66,68,72], [65,69,72,75], [67,71,75,77], [67,71,73,77],
    [69,73,76,79], [69,72,75,79],
    [60,61,64,67], [62,63,65,69], [65,66,69,72], [67,68,71,74],
    [60,62,63,67], [62,64,65,69], [65,67,68,72], [67,69,70,74],
    [48,55,60,64,67], [50,57,62,65,69], [53,60,65,69,72], [55,62,67,71,74],
    [57,64,69,72,76], [46,53,58,62,65], [43,50,55,59,62], [45,52,57,60,64],
    [72,76,79], [74,77,81], [77,81,84], [79,83,86], [81,84,88],
    [72,76,79,83], [74,77,81,84], [77,81,84,88], [79,83,86,89], [81,84,88,91],
]

# Backwards-friendly lowercase name.
chords = CHORDS


# =============================================================================
# Group parser / command-line demo
# =============================================================================


def parse_group(spec: str) -> FiniteGroup:
    """
    Parse useful short names:
      D4, C8, S4, A4, V4/K4, Q8, abelian:2,9,5
    """
    s = spec.strip().upper()
    if s in ("V4", "K4", "KLEIN"):
        return KleinFourGroup()
    if s in ("Q8", "QUATERNION"):
        return QuaternionGroup()
    if s.startswith("ABELIAN:"):
        mods = [int(x.strip()) for x in spec.split(":", 1)[1].split(",") if x.strip()]
        return AbelianGroup(mods)
    if len(s) >= 2 and s[0] in "CDSA" and s[1:].isdigit():
        n = int(s[1:])
        if s[0] == "C":
            return CyclicPermutationGroup(n)
        if s[0] == "D":
            return DihedralGroup(n)
        if s[0] == "S":
            return SymmetricGroup(n)
        if s[0] == "A":
            return AlternatingGroup(n)
    raise ValueError(f"Unknown group specification: {spec!r}")


def _demo():
    import argparse

    parser = argparse.ArgumentParser(description="Generate group-driven MIDI in pure Python.")
    parser.add_argument("--output", default="group_D4_iter_2_python.mid")
    parser.add_argument("--group", default="D4", help="e.g. D4, C8, S3, A4, Q8, abelian:2,9,5")
    parser.add_argument("--tempo", type=float, default=80)
    parser.add_argument("--voices", type=int, default=5)
    parser.add_argument("--iter", dest="iter_it", type=int, default=2)
    parser.add_argument("--base-duration", type=float, default=1 / 7)
    parser.add_argument("--chord-change-every", type=int, default=3)
    parser.add_argument("--constant", default="exp(-pi)", choices=["pi", "exp(-pi)"])
    parser.add_argument("--pi-digits", type=int, default=10000)
    args = parser.parse_args()

    G0 = parse_group(args.group)
    # Match the old example: first replace G by its regular permutation representation.
    G = regular_permutation_group(G0)["group"]
    print("Base group:", G0, "order", G0.order())
    print("Regular permutation group:", G, "order", G.order())
    print("Generators:", G.generators())

    data = group_music(
        G,
        CHORDS,
        tempo=args.tempo,
        base_duration=args.base_duration,
        octave_range=(-2, 2),
        pi_nr=args.constant,
        pi_digits=args.pi_digits,
        voices=args.voices,
        chord_change_every=args.chord_change_every,
        iter_it=args.iter_it,
    )
    write_pitches(
        args.output,
        data,
        tempo=args.tempo,
        instrument=[0] * len(data),
        add21=False,
        start_at=[0.0] * len(data),
        durations_in_quarter_notes=False,
    )


if __name__ == "__main__":
    _demo()
